//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAssignmentAug19
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTbl
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public Nullable<int> PRate { get; set; }
        public Nullable<int> BookId { get; set; }
    
        public virtual BookTable BookTable { get; set; }
    }
}
