// <auto-generated />
namespace WebMvcTill22Aug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editedgenreid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedgenreid));
        
        string IMigrationMetadata.Id
        {
            get { return "202008221049539_edited genre id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
