//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTbl
    {
        public int empId { get; set; }
        public string empName { get; set; }
        public Nullable<double> empSal { get; set; }
        public Nullable<int> deptId { get; set; }
    
        public virtual DepartmentTbl DepartmentTbl { get; set; }
    }
}
